<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in to start your session_email</name>
   <tag></tag>
   <elementGuidId>b713a46f-ec23-4d0c-9c47-1bbc47be4f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign-in-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign-in-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3c4647f-4b9c-43c2-a0a5-89be4c17cc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-in-email</value>
      <webElementGuid>c1762e83-38bd-42ba-807c-b186eafc25fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e0deebe5-baf0-48bc-9e18-481c371b5082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c3947d8-0ea8-4386-a601-44cbeefdcf3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8eed30ab-fe0e-48ce-ad3a-61690b097676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email</value>
      <webElementGuid>99087503-33db-4d5d-b9a6-b5b7ab720386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-in-email&quot;)</value>
      <webElementGuid>17a7227d-aef4-4fda-9116-cafda47665cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign-in-email']</value>
      <webElementGuid>533c5938-743a-44c0-9d24-1e76467856ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form']/form/div/input</value>
      <webElementGuid>2f6bba92-1723-42e9-aa83-6cf53128eb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7864f804-3d14-4369-adea-0c5587f5edfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sign-in-email' and @type = 'email' and @name = 'email' and @placeholder = 'Enter Email']</value>
      <webElementGuid>59b29c6d-bfe3-4a78-9e33-071ea2283a63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
