<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign out_img-responsive</name>
   <tag></tag>
   <elementGuidId>d721a235-d11b-4267-b224-40072a69eeb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menubar > div.app-user > div.media > div.media-left > div.avatar.avatar-md.avatar-circle.dropdown > a > img.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='menubar']/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>41f6a047-f065-42dc-becd-642e7f29d2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>baaf7be0-13f3-4280-b29e-c232f0c6bcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://php.inheritxdev.in/pro_value/qa/bower_components/infinity_admin/assets/images/default-avatar.png</value>
      <webElementGuid>79220757-5bd8-4fc2-9967-746117512e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>970b2ef9-9f6f-4d5b-90f3-858418112acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menubar&quot;)/div[@class=&quot;app-user&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-left&quot;]/div[@class=&quot;avatar avatar-md avatar-circle dropdown&quot;]/a[1]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>bc51bc20-e21f-4df8-9af2-811876628e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='menubar']/div/div/div/div/a/img</value>
      <webElementGuid>dfad10c9-a443-4280-a97c-cbb89704c913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='avatar'])[2]</value>
      <webElementGuid>4fa290ae-873f-441e-b7ec-8615633b6faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/div/a/img</value>
      <webElementGuid>d47568bf-f7a9-467e-b882-d8a9ff217416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://php.inheritxdev.in/pro_value/qa/bower_components/infinity_admin/assets/images/default-avatar.png' and @alt = 'avatar']</value>
      <webElementGuid>7bdce19d-7ca4-4fea-ba88-1e4bb6655fa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
